### PR TITLE
Fix for broken regex at SQLBind::parseSQL

### PR DESCRIPTION
**Pull request by jackraymund**
In project byjq/migrate I just want to migrate plain queries extracted from MySQL general log.
Where data contains ' symbols. And it dont realy match with "~'.*?'~" regex from SQLBInd::parseSQL function.
And it destroys sql's.
There is example sql
`INSERT INTO `wp_posts` (`post_author`, `post_date`, `post_date_gmt`, `post_content`, `post_excerpt`, `comment_status`, `post_title`, `post_name`, `post_modified`, `post_modified_gmt`, `guid`, `post_type`, `to_ping`, `pinged`, `post_content_filtered`) VALUES (1, '2020-12-31 01:41:02', '2020-12-31 01:41:02', '<!-- wp:paragraph -->\n<p>This is an example page. It\'s different from a blog post because it will stay in one place and will show up in your site navigation (in most themes). Most people start with an About page that introduces them to potential site visitors. It might say something like this:</p>\n<!-- /wp:paragraph -->\n\n<!-- wp:quote -->\n<blockquote class=\"wp-block-quote\"><p>Hi there! I\'m a bike messenger by day, aspiring actor by night, and this is my website. I live in Los Angeles, have a great dog named Jack, and I like pi&#241;a coladas. (And gettin\' caught in the rain.)</p></blockquote>\n<!-- /wp:quote -->\n\n<!-- wp:paragraph -->\n<p>...or something like this:</p>\n<!-- /wp:paragraph -->\n\n<!-- wp:quote -->\n<blockquote class=\"wp-block-quote\"><p>The XYZ Doohickey Company was founded in 1971, and has been providing quality doohickeys to the public ever since. Located in Gotham City, XYZ employs over 2,000 people and does all kinds of awesome things for the Gotham community.</p></blockquote>\n<!-- /wp:quote -->\n\n<!-- wp:paragraph -->\n<p>As a new WordPress user, you should go to <a href=\"http://home.home.lcl/wordpress/wp-admin/\">your dashboard</a> to delete this page and create new pages for your content. Have fun!</p>\n<!-- /wp:paragraph -->', '', 'closed', 'Sample Page', 'sample-page', '2020-12-31 01:41:02', '2020-12-31 01:41:02', 'http://xxx.lcl/wordpress/?page_id=2', 'page', '', '', '');`

### CODE REVIEW

**Comment by byjg** [comment]
Hello, thank you for your PR. I created some unit tests to validate the scenario you described in the `migration` project and as you can see in the next version https://github.com/byjg/migration/pull/31 and you are right!! The `anydataset-db` destroys the SQL when escaping single-quotes as we can confirm in the unit test in [travis-ci](https://travis-ci.com/github/byjg/migration/builds/211654387)

So, I digged into the RegEx and I could fix it in the PR #7 in the line [43](https://github.com/byjg/anydataset-db/pull/7/files#diff-f4e4a4c82f27e15e7f278e818ed39b0afc65641f6cd09c9325c82322a62d2c63R43): 

```
'.*?((\\\\'|'').*?)*'
```

If you just run `composer update` to update the `migration` dependecies you'll can get the corrections as you can see this new build on [travis-ci](https://travis-ci.com/github/byjg/migration/builds/211654891)

I'll merge your PR to have you as code contributor, however, I can't maintain your changes in the code because the `parseSql` handles absent parameters by setting them as `null`. 

And again, I really appreciate the heads up and your time contributing to the project. Thank you :+1:

**Comment by jackraymund** [comment]
@byjg Just wanted to say, it still dont work.
"name": "byjg/migration","version": "4.1.0"
"name": "byjg/anydataset-db","version": "4.1.2"
image

Again needed to fix it by my changes.

**Comment by jackraymund** [comment]
I truncated the code, cause its too long, but there is a sample, where it fails:
(539,'cs','ga','Czech'),(540,'cs','he','צ\'כית'),(541,'cs','hi','Czech'),(542,'cs','hr','češki'),(543,'cs','hu','Cseh'),(544,'cs','hy','Czech'),(545,'cs','id','Czech')
Dump is created from mysqldump.
Value which is destroying this regex: צ'כית

**Comment by jackraymund** [comment]
https://regex101.com/r/lHf0Ps/1
also tested it with MySQL Workbench.

**Comment by byjg** [comment]
I believe I won't be able to fix it. So instead, I am accepting your solution with some modifications. 

I started a new branch [here](https://github.com/byjg/anydataset-db/compare/4.1.3?expand=1). Adding this parameter, I can control behavior only when I do not use the `parseSql`.

You can do something like this:

```php
$uri = Uri::getInstanceFromUri("mysql://root:password@localhost")
                ->withQueryKeyValue(DbPdoDriver:: DONT_BIND_PARAM , "");
```

Some tests are failing, but MySQL is working. To use this code, you can change your composer file with:

```
  "prefer-stable": false,
  "minimum-stability": "dev",
``` 


OR, you can force temporarily in your composer.json the version `4.1.3.x-dev` of the `byjg/anydataset-db`

Please, please let me know if it worked for you.

**Comment by byjg** [comment]
I believe I won't be able to fix it. So instead, I am accepting your solution with some modifications.

I started a new branch here. Adding this parameter, I can control when I do not want to use the parseSql.

You can do something like this:

$uri = Uri::getInstanceFromUri("mysql://root:password@localhost")
                ->withQueryKeyValue(DbPdoDriver::DONT_BIND_PARAM , "");
Some tests are failing, but MySQL is working. To use this code, you can change your composer file with:

  "prefer-stable": false,
  "minimum-stability": "dev",
OR, you can force temporarily in your composer.json the version 4.1.3.x-dev of the byjg/anydataset-db

Please, please let me know if it worked for you.

**Comment by byjg** [comment]
I believe I won't be able to fix it. So instead, I am accepting your solution with some modifications.

I started a new branch [here](https://github.com/byjg/anydataset-db/compare/4.1.3?expand=1). Adding this parameter, I can control *when* I do not want to use the parseSql.

You can do something like this:

```php
$uri = Uri::getInstanceFromUri("mysql://root:password@localhost")
                ->withQueryKeyValue(DbPdoDriver::DONT_BIND_PARAM , "");
```

Some tests are failing, but MySQL is working. To use this code, you can change your composer file with:

```
  "prefer-stable": false,
  "minimum-stability": "dev",
```

OR, you can force temporarily in your composer.json the version `4.1.3.x-dev` of the `byjg/anydataset-db`

Please, please let me know if it worked for you.

**Pull request closed without merging**
